# LeadConduit User Guide Configuration
title: LeadConduit User Guide
description: Comprehensive documentation for LeadConduit lead management platform
baseurl: ""
url: "https://reimagined-potato-jngm138.pages.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  # - jekyll-sitemap  # Temporarily disabled to troubleshoot URL issues
  - jekyll-seo-tag

# Theme
theme: minima

# Navigation structure
header_pages:
  - index.md

# Default settings for documentation
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude files from processing
exclude:
  - bin/
  - build/
  - data/
  - context/
  - content/
  - openapi/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.gemspec"
  - README.md

# Include only necessary directories
include: []

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false

# SEO settings
author: ActiveProspect
twitter:
  username: activeprospect
  card: summary

# Social links
social:
  name: ActiveProspect
  links:
    - https://twitter.com/activeprospect
    - https://github.com/activeprospect