import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // V1 uses autogenerated sidebar
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;