# LeadConduit User Guide Configuration
title: LeadConduit User Guide
description: Comprehensive documentation for LeadConduit lead management platform
baseurl: "/kb"
url: "https://activeprospect.github.io"
repository: activeprospect/kb

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Theme
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0

# Cayman theme customization
show_downloads: false
google_analytics:
github:
  is_project_page: false

# Logo
logo: /images/activeprospect_logo.png

# Default settings for documentation
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - bin/
  - build/
  - data/
  - context/
  - content/
  - openapi/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.gemspec"
  - README.md
  - whythisissofucked.md
  - howimgoingtofixitimmediately.md

# SEO settings
author: ActiveProspect

# Social links
social:
  name: ActiveProspect
  links:
    - https://twitter.com/activeprospect
    - https://github.com/activeprospect