# LeadConduit User Guide Configuration
title: LeadConduit User Guide
description: Comprehensive documentation for LeadConduit lead management platform
baseurl: "/kb"
url: "https://activeprospect.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitBook style settings
page_width: 900px
syntax_highlighter_style: monokai

# Sidebar settings
toc:
  enabled: true
  h_min: 1
  h_max: 3

# GitBook configuration
gitbook_version: 3.2.3

# Logo and branding
logo: /images/activeprospect_logo.png
favicon: /images/ActiveProspect_icon_logo.png

# Search
search: true

# Sharing options
sharing:
  facebook: false
  twitter: false
  google: false
  weibo: false
  instapaper: false
  vk: false
  all: false

# Footer
footer:
  copyright: "Copyright &copy; 2024 ActiveProspect"
  
# Custom CSS
extra_css:
  - /assets/gitbook/custom.css

# Theme
theme: jekyll-gitbook
remote_theme: sighingnow/jekyll-gitbook

# Default settings for documentation
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude files from processing
exclude:
  - bin/
  - build/
  - data/
  - context/
  - content/
  - openapi/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - "*.gemspec"
  - README.md
  - whythisissofucked.md
  - howimgoingtofixitimmediately.md

# SEO settings
author: ActiveProspect

# Social links
social:
  name: ActiveProspect
  links:
    - https://twitter.com/activeprospect
    - https://github.com/activeprospect